export const data = [{
  "id": 1,
  "first_name": "Reube",
  "gender": "Male"
}, {
  "id": 2,
  "first_name": "Tootsie",
  "gender": "Female"
}, {
  "id": 3,
  "first_name": "Enos",
  "gender": "Male"
}, {
  "id": 4,
  "first_name": "Vic",
  "gender": "Male"
}, {
  "id": 5,
  "first_name": "Randie",
  "gender": "Male"
}, {
  "id": 6,
  "first_name": "Brice",
  "gender": "Male"
}, {
  "id": 7,
  "first_name": "Rich",
  "gender": "Male"
}, {
  "id": 8,
  "first_name": "Rodina",
  "gender": "Female"
}, {
  "id": 9,
  "first_name": "Ferdinand",
  "gender": "Male"
}, {
  "id": 10,
  "first_name": "Mela",
  "gender": "Female"
}]